# Generated by Django 2.2 on 2020-06-06 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helpfulness', models.CharField(max_length=255)),
                ('score', models.FloatField(max_length=10)),
                ('time', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('text', models.TextField()),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userReview.Product')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=255)),
                ('profileName', models.CharField(max_length=255)),
                ('productId', models.ManyToManyField(through='userReview.Review', to='userReview.Product')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userReview.User'),
        ),
    ]
