# Generated by Django 2.2 on 2020-06-06 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userReview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='userReview.Product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='userReview.User'),
        ),
    ]
