# Generated by Django 2.2 on 2020-06-06 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userReview', '0002_auto_20200606_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userReview.Product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userReview.User'),
        ),
    ]
