# Generated by Django 2.2 on 2020-06-07 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userReview', '0004_auto_20200607_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productId',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='productId',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='profileName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='productId',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userId',
            new_name='user_id',
        ),
    ]
