# Generated by Django 2.2 on 2020-06-07 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userReview', '0005_auto_20200607_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='product',
        ),
    ]
