# Generated by Django 2.2 on 2020-06-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userReview', '0006_remove_user_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='product',
            field=models.ManyToManyField(through='userReview.Review', to='userReview.Product'),
        ),
    ]
